[copper] # let copper manage it's own config!
generation_store_dir = "/home/shrey/.copper"
max_generations = 3                          # set to 0 for keeping all generations

[system_packages]
add_cmd = "yay -S --noconfirm --needed #1"
del_cmd = "yay -R --noconfirm #1"
list = [
    "adb",
    "android-tools",
    "scrcpy",
    "xz",

    "gthumb",
    "spotdl",
    "auto-cpufreq",
    "mutter-dynamic-buffering",
    "gnome-browser-connector",
    "acpi",
    "acpi_call-dkms",
    "bash-language-server",
    "bat",
    "bc",
    "bluez",
    "bluez-utils",
    "clang",
    "cmake",
    "curl",
    "direnv",
    "exa",
    "fzf",
    "github-cli",
    "thorium-browser-bin",
    "kanata",
    "less",
    "onlyoffice-bin",
    "visual-studio-code-bin",
    "linux-zen-headers",
    "llvm",
    "man",
    "mpv",
    "neovim",
    "nitch-git",
    "noto-fonts",
    "noto-fonts-emoji",
    "npm",
    "p7zip",
    "powertop",
    "python-pip",
    "python-pipx",
    "python-pynvim",
    "ripgrep",
    "spotify-adblock",
    "starship",
    "tldr",
    "trash-cli",
    "ttf-jetbrains-mono-nerd",
    "unzip",
    "wget",
    "wl-clipboard",
    "wlr-randr",
    "zoxide",
]
[system_packages.visual-studio-code-bin]
add_cmds = ["sudo chown -R $(whoami) /opt/visual-studio-code"]

[services]
add_cmd = "sudo systemctl enable --now #1"
del_cmd = "sudo systemctl disable --now #1"
list = ["bluetooth.service", "kanata.service", "powertop.service"]

[symlinks] # in case need to track files not owned by user, define alternative sudo commands
exclude = ["config\\.toml", "\\.git.*"]

[git]
add_cmd = "rm -rf #2 && git clone #1 #2"
del_cmd = "rm -rf #1"

[[git.list]]
alias = "yay"
repo_url = "https://aur.archlinux.org/yay"
clone_dir = "/home/shrey/yay"
[[git.list]]
alias = "WhiteSur-gtk-theme"
repo_url = "https://github.com/vinceliuice/WhiteSur-gtk-theme"
clone_dir = "/home/shrey/.extras/WhiteSur-gtk-theme"
[[git.list]]
alias = "colloid-icon-theme"
repo_url = "https://github.com/vinceliuice/Colloid-icon-theme"
clone_dir = "/home/shrey/.extras/Colloid-icon-theme"
[[git.list]]
alias = "SF-Fonts"
repo_url = "https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts"
clone_dir = "/home/shrey/SF"
[[git.list]]
alias = "SF-Mono-Nerd"
repo_url = "https://github.com/epk/SF-Mono-Nerd-Font"
clone_dir = "/home/shrey/SF-Mono-Nerd"

[git.yay]
add_cmds = ["(cd /home/shrey/yay && makepkg -si)"]
del_cmds = ["sudo pacman -R yay"]
[git.WhiteSur-gtk-theme]
add_cmds = ["(cd /home/shrey/.extras/WhiteSur-gtk-theme && ./install.sh -l)"]
del_cmds = ["(cd /home/shrey/.extras/WhiteSur-gtk-theme && ./install.sh -u)"]
[git.colloid-icon-theme]
add_cmds = ["(cd /home/shrey/.extras/Colloid-icon-theme && ./install.sh)"]
[git.SF-Fonts]
add_cmds = [
    "mkdir -p /home/shrey/.local/share/fonts/",
    "mv /home/shrey/SF/* /home/shrey/.local/share/fonts/",
    "fc-cache",
]
[git.SF-Mono-Nerd]
add_cmds = [
    "mkdir -p /home/shrey/.local/share/fonts/",
    "mv /home/shrey/SF-Mono-Nerd/* /home/shrey/.local/share/fonts/",
    "fc-cache",
]
