[copper] # let copper manage it's own config!
generation_store_dir = "/home/shrey/.copper"
max_generations = 3                          # set to 0 for keeping all generations

[system_packages]
add_cmd = "paru -S --noconfirm --needed #1"
del_cmd = "paru -R --noconfirm #1"
list = [
    "aylurs-gtk-shell",
    "bun",
    "pkg-config",
    "bear",
    "bfg",
    "bash-language-server",
    "bat",
    "blueman",
    "bluez",
    "bluez-utils",
    "clang",
    "curl",
    "google-chrome",
    "exa",
    "starship",
    "fzf",
    "github-cli",
    "gnome-calculator",
    "htop",
    "hyprland",
    "hyprpicker",
    "hyprshot",
    "kitty",
    "less",
    "llvm",
    "man",
    "nautilus",
    "neovim",
    "nitch-git",
    "noto-fonts",
    "npm",
    "dconf-editor",
    "powertop",
    "python-pynvim",
    "ripgrep",
    "spotify-adblock",
    "swww",
    "tldr",
    "trash-cli",
    "ttf-jetbrains-mono-nerd",
    "unzip",
    "visual-studio-code-bin",
    "wget",
    "wl-clipboard",
    "xdg-desktop-portal-gtk",
    "xdg-desktop-portal-hyprland",
    "xdg-desktop-portal",
    "zoxide",
    "cliphist",
    "acpi_call-dkms",
    "linux-zen-headers",
    "pavucontrol",
    "eog",
]

[systemd_services]
add_cmd = "sudo systemctl enable --now #1"
del_cmd = "sudo systemctl disable --now #1"
list = ["bluetooth.service", "powertop.service"]

[symlinks] # in case need to track files not owned by user, define alternative sudo commands
sudo_add_cmd = "sudo mkdir -p $(dirname #2) && sudo ln -s #1 #2"
sudo_del_cmd = "sudo rm -rf #1"

[git]
add_cmd = "git clone #1 #2"
