[copper] # let copper manage it's own config!
generation_store_dir = "/home/ferric/.copper"
max_generations = 3                          # set to 0 for keeping all generations

[system_packages]
add_cmd = "yay -S --noconfirm --needed #1"
del_cmd = "yay -R --noconfirm #1"
list = [
    "gvfs",
    "visual-studio-code-bin",
    "gvfs-mtp",
    "gvfs-gphoto2",
    "gvfs-afc",
    "hyprpolkitagent",
    "libinput-config-git",
    "libreoffice-fresh",
    "sof-firmware",
    "blueman",
    "acpi",
    "acpi_call-dkms",
    "bat",
    "bluez",
    "bluez-utils",
    "brightnessctl",
    "btop",
    "clang",
    "cmake",
    "curl",
    "dconf-editor",
    "direnv",
    "dunst",
    "exa",
    "fzf",
    "github-cli",
    "git",
    "gnome-calculator",
    "google-chrome",
    "hyprpicker",
    "hyprshot",
    "kitty",
    "less",
    "linux-zen-headers",
    "llvm",
    "man",
    "mpv",
    "nautilus",
    "neovim",
    "noto-fonts",
    "noto-fonts-emoji",
    "npm",
    "otf-geist-mono-nerd",
    "pavucontrol",
    "powertop",
    "python-pip",
    "python-pipx",
    "python-pynvim",
    "ripgrep",
    "spotify-adblock",
    "starship",
    "swww",
    "tldr",
    "trash-cli",
    "ttf-jetbrains-mono-nerd",
    "unzip",
    "zip",
    "waybar",
    "wget",
    "wl-clipboard",
    "cliphist",
    "wofi",
    "xdg-desktop-portal",
    "xdg-desktop-portal-gtk",
    "xdg-desktop-portal-hyprland",
    "zoxide",
    "rust-src",
]
[system_packages.git]
add_cmds = [
    "git config --global user.name ferriccc",
    "git config --global user.email shrey.260904@gmail.com"
]

[services]
add_cmd = "sudo systemctl enable --now #1"
del_cmd = "sudo systemctl disable --now #1"
list = ["bluetooth.service", "powertop.service"]

[symlinks] # in case need to track files not owned by user, define alternative sudo commands
exclude = ["config\\.toml", "\\.git.*", "AU_Connect\\.8021x"]

[git]
add_cmd = "rm -rf #2 && git clone #1 #2"
del_cmd = "rm -rf #1"

[[git.list]]
alias = "yay"
repo_url = "https://aur.archlinux.org/yay"
clone_dir = "/home/ferric/yay"
[[git.list]]
alias = "colloid-theme"
repo_url = "https://github.com/vinceliuice/Colloid-gtk-theme"
clone_dir = "/home/ferric/.extras/Colloid-gtk-theme"
[[git.list]]
alias = "colloid-icon-theme"
repo_url = "https://github.com/vinceliuice/Colloid-icon-theme"
clone_dir = "/home/ferric/.extras/Colloid-icon-theme"
[[git.list]]
alias = "SF-Fonts"
repo_url = "https://github.com/sahibjotsaggu/San-Francisco-Pro-Fonts"
clone_dir = "/home/ferric/SF"
[[git.list]]
alias = "SF-Mono-Nerd"
repo_url = "https://github.com/epk/SF-Mono-Nerd-Font"
clone_dir = "/home/ferric/SF-Mono-Nerd"

[git.yay]
add_cmds = ["(cd /home/ferric/yay && makepkg -si)"]
del_cmds = ["sudo pacman -R yay"]
[git.colloid-theme]
add_cmds = ["(cd /home/ferric/.extras/Colloid-gtk-theme && ./install.sh)"]
del_cmds = ["(cd /home/ferric/.extras/Colloid-gtk-theme && ./install.sh -u)"]
[git.colloid-icon-theme]
add_cmds = ["(cd /home/ferric/.extras/Colloid-icon-theme && ./install.sh)"]
[git.SF-Fonts]
add_cmds = [
    "mkdir -p /home/ferric/.local/share/fonts/",
    "mv /home/ferric/SF/* /home/ferric/.local/share/fonts/",
    "fc-cache",
]
[git.SF-Mono-Nerd]
add_cmds = [
    "mkdir -p /home/ferric/.local/share/fonts/",
    "mv /home/ferric/SF-Mono-Nerd/* /home/ferric/.local/share/fonts/",
    "fc-cache",
]
