[copper] # let copper manage it's own config!
generation_store_dir = "/home/shrey/.copper"
max_generations = 3                          # set to 0 for keeping all generations

[system_packages]
add_cmd = "yay -S --noconfirm --needed #1"
del_cmd = "yay -R --noconfirm #1"
list = [
    # Hyprland
    "brightnessctl",
    "blueman",
    "bluez",
    "bluez-utils",
    "google-chrome",
    "gnome-calculator",
    "hyprland",
    "hyprpicker",
    "hyprshot",
    "kitty",
    "waybar",
    "wofi",
    "nautilus",
    "noto-fonts",
    "noto-fonts-emoji",
    "dconf-editor",
    "powertop",
    "spotify-adblock",
    "swww",
    "xdg-desktop-portal-gtk",
    "xdg-desktop-portal-hyprland",
    "xdg-desktop-portal",
    "cliphist",
    "acpi_call-dkms",
    "linux-zen-headers",
    "pavucontrol",
    "otf-geist-mono-nerd",

    # WSL
    "acpi",
    "bear",
    "bfg",
    "bash-language-server",
    "python-pip",
    "python-pipx",
    "bat",
    "clang",
    "p7zip",
    "curl",
    "exa",
    "starship",
    "fzf",
    "github-cli",
    "less",
    "llvm",
    "man",
    "neovim",
    "nitch-git",
    "npm",
    "python-pynvim",
    "ripgrep",
    "tldr",
    "trash-cli",
    "ttf-jetbrains-mono-nerd",
    "unzip",
    "wget",
    "wl-clipboard",
    "tmux",
    "zoxide",
]

[services]
add_cmd = "sudo systemctl enable --now #1"
del_cmd = "sudo systemctl disable --now #1"
list = ["bluetooth.service"]

[symlinks] # in case need to track files not owned by user, define alternative sudo commands
sudo_add_cmd = "sudo mkdir -p $(dirname #2) && sudo ln -s #1 #2"
sudo_del_cmd = "sudo rm -rf #1"
exclude = ["config\\.toml", "\\.git.*"]

[git]
add_cmd = "rm -rf #2 && git clone #1 #2"
del_cmd = "rm -rf #1"

[[git.list]]
alias = "yay"
repo_url = "https://aur.archlinux.org/yay"
clone_dir = "/home/shrey/yay"
[[git.list]]
alias = "fun"
repo_url = "https://github.com/ferriccc/FUN"
clone_dir = "/home/shrey/FUN"
[[git.list]]
alias = "tpm"
repo_url = "https://github.com/tmux-plugins/tpm"
clone_dir = "/home/shrey/.tmux/plugins/tpm"
[[git.list]]
alias = "colloid-theme"
repo_url = "https://github.com/vinceliuice/Colloid-gtk-theme"
clone_dir = "/home/shrey/.extras/Colloid-gtk-theme"
[[git.list]]
alias = "colloid-icon-theme"
repo_url = "https://github.com/vinceliuice/Colloid-icon-theme"
clone_dir = "/home/shrey/.extras/Colloid-icon-theme"


[git.yay]
add_cmds = ["(cd /home/shrey/yay && makepkg -si)"]
del_cmds = ["sudo pacman -R yay"]
[git.colloid-theme]
add_cmds = ["(cd /home/shrey/.extras/Colloid-gtk-theme && ./install.sh)"]
del_cmds = ["(cd /home/shrey/.extras/Colloid-gtk-theme && ./install.sh -u)"]
[git.colloid-icon-theme]
add_cmds = ["(cd /home/shrey/.extras/Colloid-icon-theme && ./install.sh)"]
